name: myapp
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6  # Mantenha apenas uma versão
  quickalert: ^1.1.0  
  cupertino_icons: ^1.0.5  # Atualize para a versão mais recente
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Rubik Mono One
      fonts:
        - asset: assets/fonts/RubikMonoOne-Regular.ttf
